- hosts: all
  become_user: root

  pre_tasks:
    - name: Install roles from Ansible Galaxy
      command: ansible-galaxy install {{ item }}
      with_items:
        - "benjamin-smith.ondrej-php-repo"
        - "geerlingguy.mysql"
        - "dev-sec.mysql-hardening"
        - "jdauphant.nginx"
        - "dev-sec.nginx-hardening"
        - "geerlingguy.php-versions"
        - "geerlingguy.php"
        - "geerlingguy.composer"
        - "geerlingguy.nodejs"
        - "ocha.yarn"
        - "franklinkim.environment"