---
- name: Restart service mysql
  service:
    name: "{{ mysql_daemon }}"
    state: restarted
    sleep: 5
- name: Restart service php
  service:
    name: "php{{ php-version }}-fpm"
    state: restarted
- name: Restart service nginx
  service:
    name: "nginx"
    state: restarted